### PR TITLE
[Avatar] Fix error when name is falsey

### LINKED ISSUE #247: Avatar breaks when name=""
Unfortunately this bug is more severe now that errors in React 16 cause the whole tree to get unmounted.

The error happens [here](https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Avatar/Avatar.js#L23).

The name in Avatar is usually UGC and it's common for users to, e.g. set their name to `""`.

### PR DESCRIPTION
**Pull request by bradencanderson**
Fixes #247

### CODE REVIEW

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 62f3b12fae5ce85e7e1f20aad3c3b519403931b9

https://deploy-preview-248--gestalt.netlify.com

File: packages/gestalt/src/Avatar/Avatar.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ const Square = (props: *) => (
 );
 
 const DefaultAvatar = ({ name }: { name: string }) => {
-  const firstInitial = [...name][0].toUpperCase();
+  const firstInitial = name ? [...name][0].toUpperCase() : '';
```
Comment (pfarejowicz) [inline packages/gestalt/src/Avatar/Avatar.js]: Since react renders empty strings into the DOM should that be a null or undefined?

**Comment by christianvuerings** [comment]
Deploy preview for *gestalt* ready!

Built with commit 6a85e2113512152caaa7bb0f0b09688f71b44ec7

https://deploy-preview-248--gestalt.netlify.com

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Bundle size increase
  </td>
    </tr>
  </tbody>
</table>



Filename | Size Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip
--- | --- | --- | --- | --- | --- | --- |
gestalt.js | :small_red_triangle: 0.0% | :small_red_triangle: 0.0% | 268.24 KB | 268.25 KB | 59.53 KB | 59.54 KB
gestalt.es.js | :small_red_triangle: 0.0% | :small_red_triangle: 0.0% | 265.62 KB | 265.63 KB | 59.17 KB | 59.18 KB
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

File: packages/gestalt/src/Avatar/Avatar.js (hunk 1 above)
Comment (bradencanderson) [reply packages/gestalt/src/Avatar/Avatar.js]: Both seem equivalent from an end-user perspective. What's wrong with empty strings in the DOM?

Comment (pfarejowicz) [reply packages/gestalt/src/Avatar/Avatar.js]: Feels dirty, Airbnb has a rule of always explicitly checking against an empty string or a 0 instead of relying on the implicit Boolean conversion so that you don’t get empty strings and 0s in the DOM when you do a conditional render. This sort of feels the same lines. Just thought we should make gestalt as clean as possible for all users

Comment (bradencanderson) [reply packages/gestalt/src/Avatar/Avatar.js]: It sounds like you're talking about 2 different issues - (1) the implicit boolean conversion and (2) putting an empty string in the DOM. No opinion on either in general, but I think in this specific case they're both safe. If the reviewer has an opinion I'm happy to update.

Comment (pfarejowicz) [reply packages/gestalt/src/Avatar/Avatar.js]: Agreed - leaving it up to @christianvuerings

Comment (christianvuerings) [reply packages/gestalt/src/Avatar/Avatar.js]: @bradencanderson @pfarejowicz I'm ok with the empty string in this case. However, we should conditionally render the SVG (within the `Square`) below so we don't render DOM that's not required.

```jsx
<Square color="gray" shape="circle">
  {firstInitial && <svg
```
