### PR TITLE
Flyout: Fix caret appearance in dark mode

### LINKED ISSUE #983: Fix dark mode caret color on Flyout
The caret is dark black with white border instead of elevated color

### PR DESCRIPTION
**Pull request by jennyscript**
Closes #983 

Before
Screen Shot 2020-07-08 at 4 59 53 PM

After
Screen Shot 2020-07-08 at 4 59 27 PM

- [ ] Accessibility checkup
- [ ] Update documentation
- [ ] Add/update Tests
- [ ] Pinterest Designer (for design changes)
- [ ] [Format PR title](https://github.com/pinterest/gestalt/#releasing): `ComponentName: Description`.

### CODE REVIEW

File: packages/gestalt/src/Contents.js [hunk 1]
```diff
@@ -564,3 +582,14 @@ export default class Contents extends React.Component<Props, State> {
     );
   }
 }
+
+export default function Contents(props: OwnProps): React.Node {
```
Comment (chrislloyd) [inline packages/gestalt/src/Contents.js:586]: Instead  of having to wrap this to get the hook, could it reference the Context directly?

Comment (jennyscript) [reply packages/gestalt/src/Contents.js:586]: I could export a render prop context consumer and use that instead for class components. Do you think that's something we should export externally as well?
